### ISSUE TITLE
SleekXMPP reconnect workaround

### ISSUE THREAD

**Issue by ammgws** [ammgws/ammcon#6]
Error using workaround in latest commit : 
### 
> 2016-07-29 02:09 sleekxmpp.xmlstream.xmlstream DEBUG    Event triggered: connected
> 2016-07-29 02:09 sleekxmpp.xmlstream.xmlstream ERROR    Error processing event handler: None
> Traceback (most recent call last):
>   File "/home/xxx/py3env-ammcon/lib/python3.2/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1173, in event
>     handler[0](out_data)
> TypeError: 'NoneType' object is not callable
> 2016-07-29 02:09 sleekxmpp.basexmpp ERROR    'NoneType' object is not callable
> Traceback (most recent call last):
>   File "/home/xxx/py3env-ammcon/lib/python3.2/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1173, in event
>     handler[0](out_data)
> TypeError: 'NoneType' object is not callable

**Comment by ammgws** [comment]
Fixed [here](https://github.com/ammgws/ammcon/commit/2a9cf905d36b709e8156a0e155186b65c196f78a)
